/**:
  ros__parameters:
    joint_limits:
      # UR3 Joints
      shoulder_pan_joint:
        has_velocity_limits: true
        max_velocity: 3.14
        has_acceleration_limits: true
        max_acceleration: 5.0
      shoulder_lift_joint:
        has_velocity_limits: true
        max_velocity: 3.14
        has_acceleration_limits: true
        max_acceleration: 5.0
      elbow_joint:
        has_velocity_limits: true
        max_velocity: 3.14
        has_acceleration_limits: true
        max_acceleration: 5.0
      wrist_1_joint:
        has_velocity_limits: true
        max_velocity: 6.28
        has_acceleration_limits: true
        max_acceleration: 5.0
      wrist_2_joint:
        has_velocity_limits: true
        max_velocity: 6.28
        has_acceleration_limits: true
        max_acceleration: 5.0
      wrist_3_joint:
        has_velocity_limits: true
        max_velocity: 6.28
        has_acceleration_limits: true
        max_acceleration: 5.0

      # Gripper Joints
      gripper_finger_joint:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 2.0
      gripper_finger2_joint:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 2.0