move_group:
  ros__parameters:
    planning_plugin: "ompl_interface/OMPLPlanner"
    request_adapters: [default_planner_request_adapters/AddTimeOptimalParameterization, default_planner_request_adapters/ResolveConstraintFrames, default_planner_request_adapters/FixWorkspaceBounds, default_planner_request_adapters/FixStartStateBounds, default_planner_request_adapters/FixStartStateCollision, default_planner_request_adapters/FixStartStatePathConstraints]
    start_state_max_bounds_error: 0.1
    planning_pipeline: ompl

    planner_configs:
      RRTConnectkConfigDefault:
        type: geometric::RRTConnect
      RRTstarkConfigDefault:
        type: geometric::RRTstar
      TRRTkConfigDefault:
        type: geometric::TRRT

    ur_manipulator:
      default_planner_config: RRTConnectkConfigDefault
      planner_configs:
        - RRTConnectkConfigDefault
        - RRTstarkConfigDefault
        - TRRTkConfigDefault
      projection_evaluator: joints(shoulder_pan_joint,shoulder_lift_joint)
      longest_valid_segment_fraction: 0.005

    gripper:
      default_planner_config: RRTConnectkConfigDefault
      planner_configs:
        - RRTConnectkConfigDefault

planning_pipelines:
  pipeline_names: [ompl]

ompl:
  ros__parameters:
    planning_plugin: "ompl_interface/OMPLPlanner"
