<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="ur3_colored_shapes">
    <!-- Parameters -->
    <!-- Using the built-in pi constant from xacro -->
    <!-- <xacro:property name="pi" value="3.1415926535897931"/> -->

    <!-- Materials -->
    <material name="UR_Blue">
      <color rgba="0.1 0.1 0.8 1.0"/>
    </material>

    <material name="Grey">
      <color rgba="0.7 0.7 0.7 1.0"/>
    </material>

    <!-- UR3 specific dimensions -->
    <xacro:property name="shoulder_height" value="0.1519"/>
    <xacro:property name="upper_arm_length" value="0.24365"/>
    <xacro:property name="forearm_length" value="0.21325"/>
    <xacro:property name="wrist_1_length" value="0.08535"/>
    <xacro:property name="wrist_2_length" value="0.08535"/>
    <xacro:property name="wrist_3_length" value="0.08195"/>

    <!-- Links -->
    <link name="world"/>

    <link name="base_link">
      <visual>
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.075" length="0.1"/>
        </geometry>
        <material name="UR_Blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.075" length="0.1"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="4.0"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.00443333156" ixy="0.0" ixz="0.0" iyy="0.00443333156" iyz="0.0" izz="0.0072"/>
      </inertial>
    </link>

    <joint name="world_joint" type="fixed">
      <parent link="world"/>
      <child link="base_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="shoulder_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.06" length="0.1"/>
        </geometry>
        <material name="UR_Blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.06" length="0.1"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="3.7"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.010267495893" ixy="0.0" ixz="0.0" iyy="0.010267495893" iyz="0.0" izz="0.00666"/>
      </inertial>
    </link>

    <joint name="shoulder_pan_joint" type="revolute">
      <parent link="base_link"/>
      <child link="shoulder_link"/>
      <origin xyz="0 0 ${shoulder_height}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-2*pi}" upper="${2*pi}" effort="150.0" velocity="3.15"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="upper_arm_link">
      <visual>
        <origin xyz="0 0 ${upper_arm_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="0.06 0.06 ${upper_arm_length}"/>
        </geometry>
        <material name="UR_Blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${upper_arm_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="0.06 0.06 ${upper_arm_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="8.393"/>
        <origin xyz="0 0 ${upper_arm_length/2}" rpy="0 0 0"/>
        <inertia ixx="0.22689067591" ixy="0.0" ixz="0.0" iyy="0.22689067591" iyz="0.0" izz="0.0151074"/>
      </inertial>
    </link>

    <joint name="shoulder_lift_joint" type="revolute">
      <parent link="shoulder_link"/>
      <child link="upper_arm_link"/>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-2*pi}" upper="${2*pi}" effort="150.0" velocity="3.15"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="forearm_link">
      <visual>
        <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 ${forearm_length}"/>
        </geometry>
        <material name="UR_Blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 ${forearm_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="2.275"/>
        <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
        <inertia ixx="0.049443313556" ixy="0.0" ixz="0.0" iyy="0.049443313556" iyz="0.0" izz="0.004095"/>
      </inertial>
    </link>

    <joint name="elbow_joint" type="revolute">
      <parent link="upper_arm_link"/>
      <child link="forearm_link"/>
      <origin xyz="0 -0.093 ${upper_arm_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-2*pi}" upper="${2*pi}" effort="150.0" velocity="3.15"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="wrist_1_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.05"/>
        </geometry>
        <material name="UR_Blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.05"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.219"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.111172755531" ixy="0.0" ixz="0.0" iyy="0.111172755531" iyz="0.0" izz="0.21942"/>
      </inertial>
    </link>

    <joint name="wrist_1_joint" type="revolute">
      <parent link="forearm_link"/>
      <child link="wrist_1_link"/>
      <origin xyz="0 0 ${forearm_length}" rpy="0 ${pi/2} 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-2*pi}" upper="${2*pi}" effort="28.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="wrist_2_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.05"/>
        </geometry>
        <material name="UR_Blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.05"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.219"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.111172755531" ixy="0.0" ixz="0.0" iyy="0.111172755531" iyz="0.0" izz="0.21942"/>
      </inertial>
    </link>

    <joint name="wrist_2_joint" type="revolute">
      <parent link="wrist_1_link"/>
      <child link="wrist_2_link"/>
      <origin xyz="0 ${wrist_1_length} 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-2*pi}" upper="${2*pi}" effort="28.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="wrist_3_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.05"/>
        </geometry>
        <material name="UR_Blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.05"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1879"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0171364731454" ixy="0.0" ixz="0.0" iyy="0.0171364731454" iyz="0.0" izz="0.033822"/>
      </inertial>
    </link>

    <joint name="wrist_3_joint" type="revolute">
      <parent link="wrist_2_link"/>
      <child link="wrist_3_link"/>
      <origin xyz="0 0 ${wrist_2_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-2*pi}" upper="${2*pi}" effort="28.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="tool0">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.02 0.02 0.02"/>
        </geometry>
        <material name="Grey"/>
      </visual>
    </link>

    <joint name="wrist_3_link-tool0_fixed_joint" type="fixed">
      <parent link="wrist_3_link"/>
      <child link="tool0"/>
      <origin xyz="0 ${wrist_3_length} 0" rpy="${pi/2} 0 0"/>
    </joint>
</robot>
