material UR_Silver
{
  technique
  {
    pass
    {
      ambient 0.8 0.8 0.8 1.0
      diffuse 0.8 0.8 0.8 1.0
      specular 0.9 0.9 0.9 1.0
      shininess 50.0
    }
  }
}

material UR_Blue
{
  technique
  {
    pass
    {
      ambient 0.0 0.5 0.8 1.0
      diffuse 0.0 0.5 0.8 1.0
      specular 0.1 0.6 0.9 1.0
      shininess 50.0
    }
  }
}
