mesh_files:
  base:
    visual:
      mesh:
        package: ur3_pick_place
        path: meshes/visual/base.dae
      material:
        name: "UR_Silver"
        color: "0.8 0.8 0.8 1.0"
      texture:
        package: ur3_pick_place
        path: textures/silver.png
    collision:
      mesh:
        package: ur3_pick_place
        path: meshes/collision/base.stl

  shoulder:
    visual:
      mesh:
        package: ur3_pick_place
        path: meshes/visual/shoulder.dae
      material:
        name: "UR_Silver"
        color: "0.8 0.8 0.8 1.0"
    collision:
      mesh:
        package: ur3_pick_place
        path: meshes/collision/shoulder.stl

  upper_arm:
    visual:
      mesh:
        package: ur3_pick_place
        path: meshes/visual/upperarm.dae
      material:
        name: "UR_Silver"
        color: "0.8 0.8 0.8 1.0"
    collision:
      mesh:
        package: ur3_pick_place
        path: meshes/collision/upperarm.stl

  forearm:
    visual:
      mesh:
        package: ur3_pick_place
        path: meshes/visual/forearm.dae
      material:
        name: "UR_Silver"
        color: "0.8 0.8 0.8 1.0"
    collision:
      mesh:
        package: ur3_pick_place
        path: meshes/collision/forearm.stl

  wrist_1:
    visual:
      mesh:
        package: ur3_pick_place
        path: meshes/visual/wrist1.dae
      material:
        name: "UR_Silver"
        color: "0.8 0.8 0.8 1.0"
    collision:
      mesh:
        package: ur3_pick_place
        path: meshes/collision/wrist1.stl
    visual_offset: -0.085

  wrist_2:
    visual:
      mesh:
        package: ur3_pick_place
        path: meshes/visual/wrist2.dae
      material:
        name: "UR_Silver"
        color: "0.8 0.8 0.8 1.0"
    collision:
      mesh:
        package: ur3_pick_place
        path: meshes/collision/wrist2.stl
    visual_offset: -0.083

  wrist_3:
    visual:
      mesh:
        package: ur3_pick_place
        path: meshes/visual/wrist3.dae
      material:
        name: "UR_Silver"
        color: "0.8 0.8 0.8 1.0"
    collision:
      mesh:
        package: ur3_pick_place
        path: meshes/collision/wrist3.stl
    visual_offset: -0.082
    visual_offset_xyz: "0 -0.00255 -0.082"
